# Generated by Django 3.2.4 on 2021-06-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_projects12'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects12',
        ),
    ]
