# Generated by Django 3.2.4 on 2021-11-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0013_alter_about_us_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_model_form',
            name='message',
            field=models.TextField(max_length=10000),
        ),
    ]
