# Generated by Django 3.2.4 on 2021-11-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0018_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('dates', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
