# Generated by Django 3.2.4 on 2021-11-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0021_auto_20211113_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_history',
            name='history',
            field=models.CharField(max_length=1000),
        ),
    ]
