# Generated by Django 4.0.1 on 2022-03-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0022_alter_work_history_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployed_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField(default=0)),
                ('House_Type', models.CharField(choices=[('h', 'house,cottage,villa, semi,terrace'), ('u', 'duplex'), ('t', 'townhouse')], default='select housetype', max_length=100)),
                ('number_of_bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('number_of_car_spots', models.IntegerField(default=0)),
                ('landsize', models.FloatField(default=0.0)),
                ('building_area', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Pickle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickle_file', models.FileField(upload_to='naga/')),
            ],
        ),
    ]
