# Generated by Django 3.2.4 on 2022-04-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0023_deployed_data_pickle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text_speech_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=10000)),
            ],
        ),
    ]
