# Generated by Django 3.2.4 on 2021-06-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_mail_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail_form',
            old_name='header',
            new_name='subject',
        ),
    ]
