# Generated by Django 3.2.4 on 2021-06-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_rename_header_mail_form_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('summary', models.CharField(max_length=254)),
            ],
        ),
    ]
