# Generated by Django 3.2.4 on 2021-06-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_profile_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_pic', models.ImageField(upload_to='images/')),
                ('job_desc', models.CharField(max_length=254)),
            ],
        ),
    ]
