# Generated by Django 3.2.4 on 2021-06-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20210611_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_pic', models.ImageField(upload_to='images/')),
                ('job_desc', models.CharField(max_length=254)),
                ('job_tools', models.CharField(max_length=254)),
            ],
        ),
    ]
