# Generated by Django 3.2.4 on 2021-06-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_alter_header_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='resume',
        ),
    ]
