# Generated by Django 3.2.4 on 2021-11-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_auto_20211112_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
