# Generated by Django 3.2.4 on 2021-11-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0014_alter_contact_model_form_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='github',
            old_name='linkedin',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='stack',
            old_name='linkedin',
            new_name='stack',
        ),
        migrations.RenameField(
            model_name='youtube',
            old_name='linkedin',
            new_name='youtubr',
        ),
    ]
