# Generated by Django 3.2.4 on 2021-11-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0016_rename_youtubr_youtube_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('working_company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('emptype', models.CharField(max_length=100)),
                ('dates', models.CharField(max_length=100)),
            ],
        ),
    ]
