# Generated by Django 3.2.4 on 2021-11-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0019_auto_20211113_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download_Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_pdf', models.FileField(upload_to='resume/')),
            ],
        ),
    ]
